blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/ChristinaLast/a-fully-on-chain-reading-group/discussions
    about: Would your comment/question/suggestion be better suited to a discussion?
